services:
  frontend:
    build: ./frontend
    ports:
      - "9696:8000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "9090:80"
    depends_on:
      - worker

  worker:
    build: ./worker
    expose:
      - "5000"
